### ISSUE TITLE
Codi

### ISSUE THREAD

**Issue by u1973215** [Influencer-Singularity-Org/InfluencerSingularityGame#4]
En aquest issue s'anirà marcant el progrés realitzat sobre les tasques relatives a la part de la **implementació i programació** del joc Influencer Singularity.

- [x] 1. Menú principal (VUE.js)

- [x] 2. Implementació del joc (Phaser.io)
> - [x] a. Minijoc **Tetris**
> - [x] b. Minijoc **Editar vídeos**
> - [ ] c. Minijoc **Decisió**
> > - [ ] Elecció botons
> > - [ ] Batalla
> - [ ] d. Minijoc **Jutjat**

- [x] 3. Sistema de guardat
> - [x] a. Afegir al menú
> - [x] b. Save
> - [x] c. Load
> - [x] d. Delete all saves

- [ ] 4. Menú de pausa (VUE.js o Phaser.io)

**Comment by u1973238** [comment]
El minijoc tetris apartat 2 a acavat, falta apartat estetica
el minijoc editar video 2 b acavat, falta acavar apartat estetic

**Comment by u1973215** [comment]
Menú principal completat.

Apartat 1 finalitzat.

**Comment by u1973215** [comment]
Implementació del joc i sistema de guardat realitzats.

Apartats 2 i 3 finalitzats.
